FROM icomputer7/ancient-ubuntu-docker:gutsy

RUN apt-get update -y && \
    apt-get install -y \
    build-essential \
    manpages-dev \
    manpages-posix-dev \
    libssl-dev \
    vim

WORKDIR /app
